### ISSUE TITLE
Add social preview to the repo

### ISSUE THREAD

**Issue by anki-code** [cafehaine/xontrib-xlsd#15]
Hi! Thank you for the xontrib!

If you open [xontrib topic on Github](https://github.com/topics/xontrib) and scroll down you'll see the cute preview images for some xontribs. This is "Social preview" image that could be uploaded in the Settings of the repo.

Please take a common screenshot of your prompt and put it to the preview image.

Thanks!

**Comment by cafehaine** [comment]
That's a good idea, I'll do it whenever $LS_COLOR support is implemented
