### ISSUE TITLE
Can the sort order match ls?

### ISSUE THREAD

**Issue by scopatz** [cafehaine/xontrib-xlsd#9]
Right now all directories are listed before regular files. Is it possible to enable everything to be sorted alphabetically or lexicographically? Thanks!

**Comment by cafehaine** [comment]
I chose this since I'm way too used to file explorers, but it makes sense.

I guess we could use another environment variable for this, with choices such as "alphabetical", "directories first", "by date", "by size", and maybe command line argument to override the behavior ?

**Comment by cafehaine** [comment]
@scopatz the last commit should cover your needs, let me know if anything's missing!

I've updated the README to indicate how to customize the sorting order.

I'll have to create a new release on pypi at some point, maybe next week.

**Comment by scopatz** [comment]
Excellent! Yeah this should work.  I'll wait for the next release!

**Comment by scopatz** [comment]
Thanks a ton!
